name: awashderash
description: AwashDerash

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  google_sign_in: ^6.1.5
  firebase_auth: ^4.10.0
  firebase_ui_auth: ^1.7.0
  firebase_ui_oauth_apple: ^1.2.10
  firebase_ui_oauth_facebook: ^1.2.8
  firebase_ui_oauth_google: ^1.2.10
  firebase_ui_oauth_twitter: ^1.2.10
  package_config: ^2.1.0
  firebase_core: ^2.16.0
  msh_checkbox: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/immage/hotel1.jpeg
    - asset/immage/hotel2.jpeg
    - asset/immage/hotel3.jpeg
    - asset/immage/hotel4.jpeg
    - asset/immage/hotel5.jpeg
    - asset/todo/todologo.jpg
    - asset/common/google.png
    - asset/common/apple.png
    - asset/common/linkedin.png
    - asset/common/facebook.png
    - asset/common/lock.png
    - asset/common/apple1.png
    - asset/cm.jpeg
    - asset/todo/add.png
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/java/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/hira/
    - android/app/src/main/kotlin/com/hira/coopay/
    - android/app/src/main/kotlin/com/hira/coopay/customer/
    - android/app/src/main/kotlin/com/hira/coopay/customer/awashderash/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/gradle/
    - android/gradle/wrapper/
    - android/.gradle/
    - android/.gradle/7.5/
    - android/.gradle/7.5/checksums/
    - android/.gradle/7.5/fileHashes/
    - android/.gradle/7.5/fileChanges/
    - android/.gradle/7.5/vcsMetadata/
    - android/.gradle/7.5/executionHistory/
    - android/.gradle/7.5/dependencies-accessors/
    - android/.gradle/vcs-1/
    - android/.gradle/buildOutputCleanup/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
